
spring:
  jpa:

    generate-ddl: 'true'
    database: POSTGRESQL
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: update


  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username : postgres
    password: admin

server:
  port: 8091

